### ISSUE TITLE
Example link broken

### ISSUE THREAD

**Issue by coolcfxp** [cmake-maven-project/cmake-maven-project#45]
In README it mentioned an example but whose link is borken: https://bitbucket.org/cowwoc/requirements.java/src/759c13be200744e31f0d3f1c6df5d49ac079dfbf/natives/pom.xml#lines-69

Seems this project is not updated for quite a long time, is it not maintianed any more, or there are alternatives which can build native dependencies (other than just writing separate scripts)?

**Comment by cowwoc** [comment]
Thank you for reporting the broken link. I've fixed it. Can you please try again?

This plugin is fairly mature which is why you won't find recent commits. That said, we fix any reported bugs and add new features as needed. There are other plugins that build native dependencies (e.g. https://www.mojohaus.org/maven-native/native-maven-plugin/) but in my opinion they are much harder to maintain and debug. The main advantage of using CMake is that it generates project files (Visual Studio, XCode, Make, etc) that you can use to debug/profile your native code.

Please try it out and let me know if you run into any problems. Otherwise, feel free to close this issue.

**Comment by coolcfxp** [comment]
Thanks for fixing the link, it turned out to be just in the project files...
Glad to hear that this plugin is still maintained, I am confident enough to try it out and use it in production later on.
