### ISSUE TITLE
Override/eliminate vulnerable `commons-beanutils-1.7.0` transitive dependency

### ISSUE THREAD

**Issue by uentity** [cmake-maven-project/cmake-maven-project#63]
Hi!

After using this plugin to compile C++ components of Java library, a new dependency `commons-beanutils-1.7.0` happens to be resolved as a result. And it can't pass our vulnerability scanner. None of available approaches I could find online worked to prevent inclusion of outdated commons-beanutils. Can you please give any hint on how to achieve that?

I'm personally a C++ dev happened to work on a Java based project, at least in terms of cooperation with C++ components. So, not a proficient user of Maven, but I tried all the receipts I could find related to dependencies management in Maven. Actually, I not quite understand the chain of dependencies and/or events leading to pulling `commons-beanutils-1.7.0`.

Long story short, I'd be grateful for any information on that topic.
Thanks.

**Comment by cowwoc** [comment]
Hi @uentity 

I don't understand where the dependency of commons-beanutils-1.7.0 is coming from. When I run `mvn dependency:tree` I don't see any mention of it, so how do you see it as a dependency?

**Comment by cowwoc** [comment]
Ah, I figured it out. I had to run `mvn clean install dependency:tree -Dverbose dependency:resolve-plugins`

Anyway, to answer your question, this dependency is not a security concern. There are two kinds of dependencies:

1. The ones we use to build our plugin (build-time)
2. The ones you inherit when you use our plugin (runtime)

According to what I see, commons-beanutils is used by the following build-time plugins:

1. org.apache.maven.plugins:maven-site-plugin:maven-plugin:4.0.0-M11:runtime
2. org.sonatype.plugins:nexus-staging-maven-plugin:maven-plugin:1.6.13:runtime
3. org.apache.maven.plugins:maven-javadoc-plugin:maven-plugin:3.6.0:runtime

This is baked directly into Maven itself so it is impossible for us to get rid of. But again, this shouldn't be a security concern because it's only used to build our plugin. It isn't used when you just use the plugin.

Does that help?

**Comment by cowwoc** [comment]
@uentity Yes, we should be able to upgrade the dependency version of a plugin so long as it is binary-compatible with the older version. The better approach is to contact the plugin author and ask them to update the dependency on their end.

Which plugin do you think is relying on an on-out-date version of commons-beanutils?

**Comment by cowwoc** [comment]
I figured it out.

You need to run `mvn clean install dependency:tree -Dverbose dependency:resolve-plugins -X` (notice the -X I added at the end).

Two plugins depended on version 1.7.0: the Javadoc plugin and the Site plugin.

If I upgrade the Javadoc plugin from 3.6.0 to 3.6.3 and the Site plugin from 4.0.0-M11 to 4.0.0-M13 then all the commons-beanutils dependencies gets upgraded to 1.9.4.

Try this on your end:

```
	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-javadoc-plugin</artifactId>
					<version>3.6.3</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-site-plugin</artifactId>
					<version>4.0.0-M13</version>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>
```

and let me know if it works.

**Comment by cowwoc** [comment]
We are using the same version you are. See https://github.com/cmake-maven-project/cmake-maven-project/blob/cc74fd427b3dd387cf7a96e498b11ef049d42315/pom.xml#L149

```
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-dependency-plugin</artifactId>
  <version>3.6.1</version>
</plugin>
```

**Comment by cowwoc** [comment]
@uentity Out of curiosity, why are you unable to upgrade your version of Maven or invoke `./mvn` from the root directory which would automatically use the correct version?

Also, what do you plan to use as a replacement to cmake through Maven?

**Comment by cowwoc** [comment]
Makes sense. Thanks for the clarification.
